// 生成的文件,别手改:改 design/ 下的 JSON,再跑 python3 tools/gen_mobile_design.py。

/// 告警标题按种类(kind):``(英文, 中文)``。来源 ``design/i18n/alerts.json``。
const Map<String, (String, String)> alertTitles = <String, (String, String)>{
  'stuck': ('Waypoint not reached', '点位没到'),
  'intrusion': ('Intrusion', '有人闯入'),
  'intrusion_unanswered': ('Intrusion not answered', '闯入没人处理'),
  'intrusion_person': ('Intruder confirmed', '确认有人闯入'),
  'deter_cornered': ('Robot cornered during deterrence', '驱离时狗被逼到角落'),
  'battery_abort': ('Low battery, stopped on the way back', '电量不足，回程停在半路'),
  'run_abort': ('Could not return, stopped on the way', '没能回待命点，停在半路'),
  'archive_failed': ('Patrol record could not be saved', '巡逻记录存不下'),
  'fallen': ('Robot fell over', '狗跌倒了'),
  'loc_lost_paused': ('Localization lost, needs someone on site', '定位丢失，要人到场'),
  'charge_failed': ('Auto-charging failed', '自动回充没成'),
  'dock_stuck': ('Robot may be stuck on the dock', '狗可能卡在充电桩上'),
  'charge_overlap': ('Two robots charging, area uncovered', '两台同时在充，区域暂时没狗守'),
  'dog_sees_person': ('Person detected', '发现人员'),
  'evidence_plain': ('Evidence on robot is not encrypted', '狗上的证据没加密'),
  'evidence_unopened': ('Sealed evidence cannot be opened', '封好的证据解不开'),
  'evidence_seal_failed': ('Evidence could not be sealed', '证据封不上'),
  'force_flipped': ('Robot flipped over', '狗翻倒了'),
  'force_lifted': ('Robot was lifted', '狗被抱起来了'),
  'force_bump': ('Robot was bumped', '狗被撞了一下'),
  'force_config_bad': ('Force thresholds unreadable, using defaults', '受力门槛读不懂，用缺省值'),
  'purged_incoming_stuck': ('Deleted evidence could not be removed', '已删证据删不掉'),
  'backup_verify_failed': ('Site backup failed verification', '站点备份校验没过'),
  'push_failed': ('P1 push notifications failing', 'P1 推送发不出去'),
  'cert_expiring': ('Certificate expiring soon', '证书快到期'),
  'site_disk_low': ('Site disk almost full', '站点盘快满了'),
  'lane_stuck': ('Site background task stuck', '站点后台任务卡住了'),
  'agent_too_old': ('Robot software too old', '狗上的代理太老'),
  'site_too_old': ('Site software older than robot', '站点比狗上的代理老'),
  'loc_degraded': ('Localization degraded, robot paused', '定位变差，原地等恢复'),
  'estop_pressed': ('E-stop pressed', '急停被按下'),
  'lease_expired': ('Supervision lease expired', '监护超时'),
  'suspend_stale': ('Robot paused too long', '暂停太久'),
  'watchdog_died': ('Site watchdog stopped', '站点看门狗停了'),
  'schedule_died': ('Scheduled patrol failed', '排程没办成'),
  'schedule_missed': ('Scheduled patrol missed', '排程错过了'),
  'robot_offline': ('Robot offline during a task', '狗掉线了（跑着任务）'),
  'nogo': ('Robot inside a no-go zone', '狗在禁行区里'),
  'recording_delete_failed': ('Old recordings cannot be deleted', '旧录像删不掉'),
  'payload_strobe': ('Strobe failed', '警示灯出故障'),
  'payload_siren': ('Siren failed', '警笛出故障'),
  'payload_spotlight': ('Spotlight failed', '探照灯出故障'),
  'finding': ('Inspection finding', '判读有异常'),
  'recording_failed': ('Recording interrupted', '录像断了'),
  'agent_args_skipped': ('Unknown robot settings skipped', '狗上有启动参数不认识'),
  'recording_dropped': ('Robot recordings dropped', '狗上的录像没传上来'),
  'recording_trimmed': ('Oldest recordings removed (disk full)', '盘紧，删了最旧的录像'),
  'cctv_offline': ('Camera offline', '摄像头连不上'),
  'disk_80': ('Robot storage almost full', '狗的盘快满了'),
  'backup_stale': ('Site backup out of date', '站点备份过期了'),
  'map_failed': ('Map operation failed', '地图操作没成'),
  'map_integrity': ('Robot map is corrupted', '狗上的图坏了'),
  'rtk': ('RTK base station moved', 'RTK 基站坐标跳了'),
  'standby_failed': ('Did not return to standby', '没回待命点'),
  'upload_refused': ('Site refused an upload', '站点不收上传'),
  'release_failed': ('Software update failed', '升级没成'),
  'upload_backlog': ('Evidence upload delayed', '证据半小时没传上来'),
  'bundle_lag': ('Robot mission data out of date', '狗上的任务包落后'),
  'clock_skew': ('Robot clock is off', '狗的钟不准'),
  'schedule_skipped': ('Scheduled patrol skipped', '排程跳过了'),
  'schedule_blocked': ('Scheduled patrol blocked', '排程被拦住了'),
  'schedule_interrupted': ('Scheduled patrol interrupted', '排程被打断了'),
  'incident_flood': ('Too many events from one source', '事件源报得太多'),
  'robot_offline_idle': ('Robot offline', '狗掉线了'),
  'run_done': ('Patrol finished', '巡逻跑完了'),
  'run_start': ('Patrol started', '开始巡逻'),
  'battery_swap': ('Battery swap needed', '要换电池'),
  'authorized_person': ('Authorized person present', '授权人员在场'),
};
